### ISSUE TITLE
Blank review and blank PDFs generated while doing export on Linux 

### ISSUE THREAD

**Issue by varunu28** [salomonelli/best-resume-ever#137]
## Issue
Blank review on Linux and blank PDFs on export

## Info
- Operating System: LINUX
- Node-Version: v8.8.1

#### Step 2: Running the review on dev server
![dev server running](https://user-images.githubusercontent.com/7676016/32450430-0a5deb46-c2c9-11e7-85da-07ef44e33d84.png)
![host 8080](https://user-images.githubusercontent.com/7676016/32450470-1ce3871c-c2c9-11e7-9aa7-15b9e701be19.png)
![blank review](https://user-images.githubusercontent.com/7676016/32450459-16c73c0c-c2c9-11e7-8ea0-fa4cc632d24e.png)

The review runs on host 8080 but when I click on the template, it is blank
#### Step 3: npm run export creates the pdf in PDF folder but all the pdf are blank 
![export command runs successfully](https://user-images.githubusercontent.com/7676016/32450528-445235dc-c2c9-11e7-9944-2421b49a8751.png)
![all blank pdfs](https://user-images.githubusercontent.com/7676016/32450553-5c576e72-c2c9-11e7-91c4-65b4a5470e2d.png)

**Comment by unix-root** [comment]
+1 Getting the same issue now on OSX. Was working fine few days back. Today I edited my resume a bit and ran `npm run dev` and `npm run export` both returned blank pdfs.

**Comment by lomboboo** [comment]
+ 1, confirming that on Ubuntu 16, node v8.5.0 the same issue as described above

**Comment by lomboboo** [comment]
So after quick debuggin I found why it didn't work for me. I had nothing to do with operating system or Node. I had line like that:
```
education:
- degree: Master’s degree: Computer Science // colon ( : ) after 'degree'
```
So colon as a symbol inside string breaks the app. String should be surrounded with quotes or replacing ':' with something else.

**Comment by FabianCdx** [comment]
+1 Getting the same issue and i checked my text no colons, komma and dots still getting blank pages..

**Comment by lomboboo** [comment]
@FabianCdx , try to debug. I kept standard application ``.yml`` file and replaced each line with my own, **one by one**. Every time I replace a line I ran ``export`` to test if it works. That way you can find the line that causes the problem.

Or maybe insert here your ``yml`` file and I will try to help.

**Comment by FabianCdx** [comment]
@lomboboo thank you lomboboo i will insert the file here later when i am back at home.

**Comment by FabianCdx** [comment]
@lomboboo here's the data.yml code
```
/* #*/ export const PERSON = `
name:
  first: Roubie
  middle: Frobiae
  last: Rin-Thething
about: Hi, my name is Roubie Frobiae. I"m just about the most boring type of person you could
       possibly imagine. I like collecting leaves from the tree in my back yard and documenting
       each time I eat a peanut that is non-uniform. I am not a robot. Please hire me.
position: IT Specialist for Application Development

birth:
  year: 1997
  location: Rolitfotl

experience:
- company: KIO Shi Solution
  position: Developer
  timeperiod: since September 2017
  description: Development of alien systems

- company: Rudis GmbH
  position: Frontend Developer
  timeperiod: September 2016 - Februar 2017
  description: Shopware CMS JavaScript & CSS3

education:
- degree: Dr.-Roy-Jones-School Fueefh
  timeperiod: September 2013 - June 2015
  description: Intermediate lorem-ipsum chipripsos (Sausage)

# skill level goes 0 to 100
skills:
- name: HTML5
  level: 99
- name: CSS3
  level: 87
- name: Java
  level: 78
- name: JavaScript
  level: 50
- name: Cplusplus
  level: 45
- name: C-Sharp
  level: 60
  name: Unity
  level: 70

knowledge: Also proficient in Adobe Photoshop, Illustrator and Cinema 4D.

contact:
  email: Roubiefourbie at outlook dot com
  phone: 1337
  street: Grove Street 24
  city: Compton  California  USA
  website: Roubiefourbie dot de
  github: FabianCdx
# en, de, fr, pt, ca, cn, it, es, th, pt-br, ru, sv, id, hu, pl, ja, ka, nl, he, zh-tw, lt, ko, el
lang: en
`

```
