### ISSUE TITLE
Add milti-line job description

### ISSUE THREAD

**Issue by smoqadam** [salomonelli/best-resume-ever#305]
Hi, Thanks for this awesome project. 

When I add multi line job description, it's shown like this:

![screenshot_2018-09-10 best-resume-ever 1](https://user-images.githubusercontent.com/1223848/45278825-6215f100-b501-11e8-9e27-8bbd1d49c882.png)

 
my yaml file is like this:

```yml
 - company: MyCompany
   position: Senior PHP Developer
   timeperiod: Oct 2017 - August 2018
   description:
         - • Debug and Refactor legacy code base
         - • Collaborate with android development team to create new features
``` 
what should I do if want to add multi line job description?
